spring:
  datasource:
     name: dev
     url: jdbc:mysql://localhost:3306/bike?useSSL=false
     username: root
     password: password

  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: false

  #springdata
  data:
    # mongoDB    #mongodb note:mongo3.x will not use host and port,only use uri
    mongodb:
      uri: mongodb://localhost:27017/bike



##activeMQ
#  activemq:
#      broker-url: tcp://localhost:61616
#      pool:
#        enabled: false
##springdata
#  data:
#     # mongoDB    #mongodb note:mongo3.x will not use host and port,only use uri
#    mongodb:
#      uri: mongodb://localhost:27017/mama-bike
#
##reids
redis:
    host: 127.0.0.1
    port: 6379
    auth:
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000